server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/JaneRoad/orderingsystem.git #Git 仓库地址
          searchPaths: config #仓库路径
          username: 425999212@qq.com  #Git 仓库用户名
          password: LJN7CP3.com #Git 仓库密码
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/